### ISSUE TITLE
I can't find it in the VSCODE plugin market

### ISSUE THREAD

**Issue by mst272** [WisdomShell/codeshell-vscode#1]
I can't find it in the VSCODE plugin market

**Comment by JunzheShen** [comment]
you need to build a `codeshell-vscode-${VERSION_NAME}.vsix` file following the instructions by yourself

**Comment by weiye** [comment]
We will upload the plugin to the VSCode marketplace in the next few days.

**Comment by cyxnzb** [comment]
You can install the .vsix,and import it by yourself

**Comment by 0ut0fMem** [comment]
We have uploaded the extension to the VSCode marketplace. Enjoy it!

**Comment by xhnxhn** [comment]
> 我们已将扩展上传到 VSCode 市场。好好享受！

![image](https://github.com/WisdomShell/codeshell-vscode/assets/45118125/83d8acda-97d2-4834-b670-ea736edff60f)
构建文件报错
