### ISSUE TITLE
使用 CodeShell-7B-Chat 未量化版本模型

### ISSUE THREAD

**Issue by 4869APTX** [WisdomShell/codeshell-vscode#10]
请问codeshell的vscode插件能否调用本地部署的CodeShell-7B-Chat未量化版本的模型

**Comment by ruixie** [comment]
谢谢关注，我们正在研发IDE插件与text-generation-inference的适配，近几天将开源，敬请期待。

**Comment by 4869APTX** [comment]
感谢

**Comment by vimBashMing** [comment]
> 请问codeshell的vscode插件能否调用本地部署的CodeShell-7B-Chat未量化版本的模型

当前项目已更新，提供了对未量化的GPU版本的支持。请参考最新的README，并更新vscode-codeshell插件。
