### ISSUE TITLE
部署模型时，跑不出结果（Unable to get the result of the service to the server）

### ISSUE THREAD

**Issue by zhangymyeah** [WisdomShell/codeshell-vscode#12]
![屏幕截图 2023-10-20 140250](https://github.com/WisdomShell/codeshell-vscode/assets/148523667/a7264a7e-d9db-484a-aa42-554ffd70421b)
it will stop at here without any more process for hours!!!!
yesterday it can run further but still can't finish !!!!
I dont know why ???? truly want to find someone to help me . thanks a lot

**Comment by ruixie** [comment]
Hello, the process you've initiated is a server. This means it listens on port 8080, allowing you to communicate with it through HTTP requests or directly via our IDE plugin.

Please refer to the server documentation for more information:

https://github.com/WisdomShell/llama_cpp_for_codeshell/blob/master/examples/server/README.md

**Comment by zhangymyeah** [comment]
> Hello, the process you've initiated is a server. This means it listens on port 8080, allowing you to communicate with it through HTTP requests or directly via our IDE plugin.
> 
> Please refer to the server documentation for more information:
> 
> https://github.com/WisdomShell/llama_cpp_for_codeshell/blob/master/examples/server/README.m

> Hello, the process you've initiated is a server. This means it listens on port 8080, allowing you to communicate with it through HTTP requests or directly via our IDE plugin.
> 
> Please refer to the server documentation for more information:
> 
> https://github.com/WisdomShell/llama_cpp_for_codeshell/blob/master/examples/server/README.md

understand  and thank u very much，I successfully get the results, but it's quite slow. and don't have the funcion that aotumatic fulfill

**Comment by ruixie** [comment]
Hello! Running CodeShell exclusively on a CPU might lead to slower performance. However, running it on a Mac equipped with the M1 or M2 chip can significantly boost its speed. Moreover, with our upcoming release supporting [text-generation-inference](https://github.com/huggingface/text-generation-inference), computers equipped with Nvidia GPUs will also benefit from enhanced performance.

**Comment by vimBashMing** [comment]
> > Hello, the process you've initiated is a server. This means it listens on port 8080, allowing you to communicate with it through HTTP requests or directly via our IDE plugin.
> > Please refer to the server documentation for more information:
> > https://github.com/WisdomShell/llama_cpp_for_codeshell/blob/master/examples/server/README.m
> 
> > Hello, the process you've initiated is a server. This means it listens on port 8080, allowing you to communicate with it through HTTP requests or directly via our IDE plugin.
> > Please refer to the server documentation for more information:
> > https://github.com/WisdomShell/llama_cpp_for_codeshell/blob/master/examples/server/README.md
> 
> understand and thank u very much，I successfully get the results, but it's quite slow. and don't have the funcion that aotumatic fulfill

Please refer to the latest README and download/update the latest VSCode plugin to experience the automatic fulfill function.
