### ISSUE TITLE
vscode 左边任务栏codeshell一直连不上

### ISSUE THREAD

**Issue by Chenwe111** [WisdomShell/codeshell-vscode#13]
vscode 左边任务栏codeshell一直连不上， 服务部署之后有时候能看到底下codeshell在转动，但是不显示任何东西，请问是为什么

**Comment by vimBashMing** [comment]
方便请提供截图看下，确保本地server已经正常启动。

**Comment by Chenwe111** [comment]
![image](https://github.com/WisdomShell/codeshell-vscode/assets/93525180/babdb95a-0c0a-4720-abd3-78e9f4b679ab)

**Comment by Chenwe111** [comment]
网页是可以打开推理的，就是vscode的插件连不上，自动补全功能也没有

**Comment by vimBashMing** [comment]
请参考README，配置插件连接server的端口。同时更新本地server，在插件市场更新插件，已针对补全功能做了优化。

**Comment by Chenwe111** [comment]
> 请参考README，配置插件连接server的端口。同时更新本地server，在插件市场更新插件，已针对补全功能做了优化。

hi，我更新了插件版本和代码库，现在补全功能是有了，但是左边的codeshell界面还是没法出来
![image](https://github.com/WisdomShell/codeshell-vscode/assets/93525180/0aa2db54-83b9-40f5-b89e-f406c1d028bc)
这个是什么原因

**Comment by Chenwe111** [comment]
> 请参考README，配置插件连接server的端口。同时更新本地server，在插件市场更新插件，已针对补全功能做了优化。

右键生成注释也没法使用，麻烦帮忙看一下==

**Comment by vimBashMing** [comment]
> > 请参考README，配置插件连接server的端口。同时更新本地server，在插件市场更新插件，已针对补全功能做了优化。
> 
> 右键生成注释也没法使用，麻烦帮忙看一下==

请提供一下你本地操作系统的具体版本

**Comment by Chenwe111** [comment]
> > > 请参考README，配置插件连接server的端口。同时更新本地server，在插件市场更新插件，已针对补全功能做了优化。
> > 
> > 
> > 右键生成注释也没法使用，麻烦帮忙看一下==
> 
> 请提供一下你本地操作系统的具体版本

![image](https://github.com/WisdomShell/codeshell-vscode/assets/93525180/207b6239-5712-4c18-9904-acd91b7b2be0)
我不知道是系统问题还是vscode版本的问题，我换了一台电脑可以。当前这台不行的电脑vscode版本是1.69.0。我更新下版本试试
