### ISSUE TITLE
vscode 左边任务栏codeshell一直连不上，如何使用。

### ISSUE THREAD

**Issue by tjvip99** [WisdomShell/codeshell-vscode#17]
vscode右下角提示这个错误，如何解决啊。
h: request to http://localhost:8080/completion failed, reason: connect ECONNREFUSED 127.0.0.1:8080

**Comment by cove9988** [comment]
在浏览器看一下，可不可以？http://127.0.0.1:8080

**Comment by tjvip99** [comment]
http://127.0.0.1:8080/浏览器看了，也打不开这个网站。谷歌浏览器和EDGE浏览器都打不开

**Comment by vimBashMing** [comment]
请参照README，确保本地服务已启动。
