### ISSUE TITLE
Make 报错

### ISSUE THREAD

**Issue by majnn** [WisdomShell/codeshell-vscode#23]
![image](https://github.com/WisdomShell/codeshell-vscode/assets/55217559/2bb74ed6-88df-439d-be0e-c33a2a6c7f1e)
如图， make 错误怎么解决？

**Comment by vimBashMing** [comment]
看报错信息，你本地没有安装基础的C编译环境，cc和g++都没有安装。请先根据你的操作系统版本，先将cc和g++等基础编译环境安装上
