### ISSUE TITLE
VSCode里安装插件后一直是空的转菊花

### ISSUE THREAD

**Issue by bolt163** [WisdomShell/codeshell-vscode#29]
如题，截图如下，模型服务已启动
问题表现：在VSCode里的插件点击后，左侧加载使用的时候是空的，一直转菊花状态

<img width="961" alt="企业微信截图_e225969a-d865-4bf6-be72-4fc0de542717" src="https://github.com/WisdomShell/codeshell-vscode/assets/25170435/829994f4-f04b-4943-843d-6e527fd98a85">

本地chrome浏览器里打开可访问
<img width="945" alt="企业微信截图_6c6d800d-4a73-4928-a289-aadce77272fa" src="https://github.com/WisdomShell/codeshell-vscode/assets/25170435/d6c1d599-7886-4e4d-a6e9-cba243e6c1f8">

**Comment by vimBashMing** [comment]
请具体描述一下：是左侧的对话框里输入无响应？还是右侧代码段邮件菜单里的功能无响应？

**Comment by bolt163** [comment]
左侧，macOS  Sonoma 14
网络存在代理的情况下会有问题吗

**Comment by vimBashMing** [comment]
> 左侧，macOS Sonoma 14
> 网络存在代理的情况下会有问题吗

网络代理应该是没有影响。vscode的版本号多少？

**Comment by bolt163** [comment]
> > 左侧，macOS Sonoma 14
> > 网络存在代理的情况下会有问题吗
> 
> 网络代理应该是没有影响。vscode的版本号多少？


左侧，网络存在代理的情况下会有问题吗
OS： macOS Sonoma 14
VSCode版本: 1.78.2 (Universal)

**Comment by vimBashMing** [comment]
> > > 左侧，macOS Sonoma 14， macOS Ventura13.5  两个os版本都有类似问题
> > > 网络存在代理的情况下会有问题吗
> > 
> > 
> > 网络代理应该是没有影响。vscode的版本号多少？
> 
> 左侧，网络存在代理的情况下会有问题吗 OS： macOS Sonoma 14， macOS Ventura13.5 两个os版本都有类似问题 VSCode版本: 1.78.2 (Universal)

确认一下vscode里面nodejs的版本，需要将nodejs升级到18以上

**Comment by bolt163** [comment]
> > > > 左侧，macOS Sonoma 14， macOS Ventura13.5  两个os版本都有类似问题
> > > > 网络存在代理的情况下会有问题吗
> > > 
> > > 
> > > 网络代理应该是没有影响。vscode的版本号多少？
> > 
> > 
> > 左侧，网络存在代理的情况下会有问题吗 OS： macOS Sonoma 14， macOS Ventura13.5 两个os版本都有类似问题 VSCode版本: 1.78.2 (Universal)
> 
> 确认一下vscode里面nodejs的版本，需要将nodejs升级到18以上

node -v
v18.17.1

**Comment by 0ut0fMem0ry** [comment]
Please update your vscode to version 1.83.1

**Comment by yportne13** [comment]
有可能是 ChatMemory.ts 里 nanoid() 导致的，我给改成
```typescript
time = new Date();
id = "Uakgb_J5m9g-0JDMbcJqL" + this.time.toDateString();
```
解决了
