### ISSUE TITLE
模型下载和模型安装遇到错误提示

### ISSUE THREAD

**Issue by bitseaman** [WisdomShell/codeshell-vscode#3]
模型下载时遇到错误，看到“https://huggingface.co/WisdomShell/CodeShell-7B-Chat-int4/codeshell_q4_0.gguf”下没有codeshell_q4_0.gguf文件，只有个类似的文件codeshell-chat-q4_0.gguf。

手动下载下codeshell-chat-q4_0.gguf到models文件夹下后，安装模型提示错误
“./server : 无法将“./server”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ./server -m ./models/codeshell-chat-q4_0.gguf --host 127.0.0.1 --port ...
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./server:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException”

**Comment by JunzheShen** [comment]
因为没有运行 `make server` 吧？不过我在我的windows电脑上运行 `make server` 会报错

**Comment by bitseaman** [comment]
第二个错误的原因，您说对了。make没有运行成功。由于是win64平台，根据网上信息，下载安装了gnuwin32，设置环境变量，也在powershell设置了set-ExecutionPolicy RemoteSigned，make还是没有运行成功。

**Comment by JunzheShen** [comment]
可以看一下我新发的issue，用WSL很方便
