### ISSUE TITLE
-ngl 0 不加触发自动补齐服务就挂了，加了得10s+才能出来

### ISSUE THREAD

**Issue by 779102260** [WisdomShell/codeshell-vscode#43]
正常吗？这咋玩
mac 32g inte

**Comment by 779102260** [comment]
没。本地跑不现实



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月7日(周二) 凌晨0:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WisdomShell/codeshell-vscode] -ngl 0 不加触发自动补齐服务就挂了，加了得10s+才能出来 (Issue #43)




 
解决了吗

**Comment by vimBashMing** [comment]
请参照README。Intel芯片的Mac笔记本无法有效利用Metal架构的GPU，导致只能使用CPU推理，其效率肯定大打折扣。本地使用的话，请使用M1/M2/M3芯片的Mac

**Comment by 779102260** [comment]
那M1 代码补全大概需要多久？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月7日(周二) 上午10:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WisdomShell/codeshell-vscode] -ngl 0 不加触发自动补齐服务就挂了，加了得10s+才能出来 (Issue #43)




 
请参照README。Intel芯片的Mac笔记本无法有效利用Metal架构的GPU，导致只能使用CPU推理，其效率肯定大打折扣。本地使用的话，请使用M1/M2/M3芯片的Mac
