### ISSUE TITLE
FetchError:request to http://127.0.0.1:8080/completionfailed

### ISSUE THREAD

**Issue by Beyondpast2022** [WisdomShell/codeshell-vscode#46]
When chat with CodeShell, show error as the following:
FetchError:request to http://127.0.0.1:8080/completionfailed, reason: connect ECONNREFUSED127.0.0.1:8080
来源：CodeShell VSCode Extension（扩展）。
How to fix this issue for above?

**Comment by account310** [comment]
解决了吗

**Comment by vimBashMing** [comment]
Please refer to README, and ensure that the local model service is started.
