### ISSUE TITLE
可以把 codeshell-chat-q4_0.gguf 往魔搭社区传一份吗？

### ISSUE THREAD

**Issue by Jingzhenzxz** [WisdomShell/codeshell-vscode#47]
您好，可以把 codeshell-chat-q4_0.gguf 往魔搭社区传一份吗？我的服务器访问不了HF

**Comment by vimBashMing** [comment]
已上传到modelscope

**Comment by Jingzhenzxz** [comment]
> 已上传到modelscope

您好，请问您把 codeshell-chat-q4_0.gguf 传到哪个仓库中了呢？我在魔搭社区的codeshell-7B、codeshell-7B-Chat和codeshell-7B-Chat-int4仓库中都没有找到这个文件：
https://www.modelscope.cn/models/WisdomShell/CodeShell-7B/files
https://www.modelscope.cn/models/WisdomShell/CodeShell-7B-Chat/files
https://www.modelscope.cn/models/WisdomShell/CodeShell-7B-Chat-int4/files
