### ISSUE TITLE
Is is support deepseek coder yet ?

### ISSUE THREAD

**Issue by x4080** [WisdomShell/codeshell-vscode#48]
Hi, I was using llama cpp with deepseek coder connecting to this extension but code completion is not working (error about not string or something) but chat with server is works
Then I tried using llama_cpp_for_codeshell, it seems code completion is connecting (no error on VSCode) but the result is garbled characters

```
@@@@@@
```

The same also in chat with server

System : m2 pro

Thanks

**Comment by vimBashMing** [comment]
Currently, the plugin only supports codeshell

**Comment by x4080** [comment]
Thanks
