### ISSUE TITLE
检查性能问题，跟检查安全问题的prompts函数混淆了

### ISSUE THREAD

**Issue by carusyte** [WisdomShell/codeshell-vscode#50]
https://github.com/WisdomShell/codeshell-vscode/blob/ac8923fb2486e4e54a80cda1f34d5ec586ba276f/src/CreatePrompt.ts#L23C1-L29C2

<img width="1160" alt="image" src="https://github.com/WisdomShell/codeshell-vscode/assets/1680881/0106a716-c857-4301-a1cb-d618911e7b75">

**Comment by 0ut0fm1nd** [comment]
Thanks a lot!
