### ISSUE TITLE
插件中访问模型url添加后缀completion，模型那边部署是completions

### ISSUE THREAD

**Issue by NoobPythoner** [WisdomShell/codeshell-vscode#52]
插件中访问模型url添加后缀completion，模型那边部署是completions，
http://127.0.0.1:8000/v1/chat/completions,两边都不通，这代码咋发出来的，不自测试的吗

**Comment by AhuiZhao** [comment]
❤

**Comment by 0ut0fm1nd** [comment]
你真是个大聪明。
