### ISSUE TITLE
Deployment models

### ISSUE THREAD

**Issue by wanghuiqiang1** [WisdomShell/codeshell-vscode#6]
I used the code provided in the Readme.md to deploy the model, but an error occurred after I executed the command. Why? I have carefully examined the code path of llama_cpp_for_codeshell. thank you!

The error message is:
(base) root@9020:~/llama_cpp_for_codeshell$ ./server -m ./models/codeshell-chat-q4_0.gguf --host 127.0.0.1 --port 8185
-bash: ./server: No such file or directory

**Comment by wanghuiqiang1** [comment]
I have solved the above question and tried to run the model in 4 RTX4090, but I find the answer seems slow? Why is that?

**Comment by ruixie** [comment]
Hello! Running CodeShell exclusively on a CPU might lead to slower performance. However, running it on a Mac equipped with the M1 or M2 chip can significantly boost its speed. Additionally, our upcoming release will support [text-generation-inference](https://github.com/huggingface/text-generation-inference), so you can serve the Python version on you RTX4090 directly. Stay tuned!

**Comment by wanghuiqiang1** [comment]
Thank you for your work!
 
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/20/2023 16:40
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [WisdomShell/codeshell-vscode] Deployment models (Issue #6)
        
      
    
  

Hello! Running CodeShell exclusively on a CPU might lead to slower performance. However, running it on a Mac equipped with the M1 or M2 chip can significantly boost its speed. Additionally, our upcoming release will support text-generation-inference, so you can serve the Python version on you RTX4090 directly. Stay tuned!
